---
- name: Hello World!
  hosts: all
 
  tasks:
 
  - name: Hello World!
    shell: echo "Hi! Tower is working."
    register: result
    
  - name: Print Result
    debug: msg="{{ result.stdout }}"
   
